### ISSUE TITLE
decode before using nltk

### ISSUE THREAD

**Issue by nateanl** [nlp-psych/gender_data_assignment#1]
There is a problem if you are using the latest version of nltk package.

 In [tokenized_text = [nltk.word_tokenize(text) for text in source_text]](https://github.com/nlp-psych/gender_data_assignment/blob/master/feature_extractor.py#L17), you need to replace "text" with text.decode('utf-8').

**Comment by rivlev** [comment]
Leaving this alone because decoding breaks for me

**Comment by rivlev** [comment]
Leaving this alone because decoding breaks for me

```AttributeError: 'str' object has no attribute 'decode```

and I don't see an error without it. Use this fix if you need it.
