### ISSUE TITLE
rare words should be escaped

### ISSUE THREAD

**Issue by andreas-weise** [nlp-psych/gender_data_assignment#4]
The [rare words list](https://github.com/nlp-psych/gender_data_assignment/blob/master/feature_extractor.py#L35) needs to be escaped, otherwise some characters can be interpreted as regular expression syntax. 
This solves the issue: `rare_words_list = [re.escape(word) for word in vocab.hapaxes()]`

**Comment by rivlev** [comment]
Fixed by e0969a76148eaab0efb99f95b75f17c636d68883, thanks
